### ISSUE TITLE
Do you still support SDK 5.0

### ISSUE THREAD

**Issue by jellespijker** [fieldOfView/Cura-MeasureTool#19]
I only noticed curapackages for 6, 7 and 8 in the plugin portal

https://github.com/fieldOfView/Cura-MeasureTool/blob/d57aafebcb9ce2ec5c0b2ae8082c691042449352/plugin.json#L7

**Comment by fieldOfView** [comment]
The question is "did I ever support SDK 5 for this plugin?". I don't think I did, but just copy/pasted the supported sdk versions line from another plugin.json file.

I'll remove the 5.0.0 in the next release. I don't think it is a big issue at the moment, because there's simply no package for SDK 5 in the marketplace (though I do have one here on github), and who uses Cura 3.5-3.6 anymore anyway, right?
